import { Portfolio, PROFICIENCY, PROJECT_TYPE } from '@/context/types';
import * as assets from './asset';

export const daniel_bello: Portfolio = {
  id: '1',
  started_professions_at: '1/1/2017',
  started_programming_at: '1/1/2020',
  imgs: [
    assets.user_img1,
    assets.user_img2,
    assets.user_img3,
    assets.user_img4,
  ],
  name: {
    complete: 'adegoke adeyinka daniel bello',
    first: 'adegoke',
    last: 'bello',
    other: ['adeyinka', 'daniel'],
  },
  role: 'computer engineer',
  professional_summary:
    'A computer engineer with over 9 years of distrubuted experience in full-stack web development, mobile development and embedded systems.',
  avatar: assets.user_img1,
  nationality: 'nigerian',
  phone_number: '+1 (463) 626-0490',
  email: 'gokebello@gmail.com',
  address: {
    country: 'united-states',
    state: 'indiana',
    region: 'marion',
    street: 'beachview drive',
    apartment: '250',
    city: 'indianapolis',
    zip_code: 46224,
    address: '6033 beachview drive apt 250 indianapolis IN u.s.a',
  },
  date_of_birth: '12/13/1996',
  services: [
    {
      id: '1',
      proficiency: PROFICIENCY.EXPERT,
      skills: [
        {
          id: '1',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Javascript',
          percent: 98,
        },
        {
          id: '2',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Typescript',
          percent: 99,
        },
        {
          id: '3',
          proficiency: PROFICIENCY.EXPERT,
          title: 'NodeJS',
          percent: 99,
        },
        {
          id: '4',
          proficiency: PROFICIENCY.EXPERT,
          title: 'ReactJS',
          percent: 99,
        },
      ],
      summary:
        '8+ years professional skills in both frontend and backend web development, using tools like React, ASP.NET-CORE, NodeJS etc as well as DevOps developments.',
      title: 'Full Stack Web Development',
    },
    {
      id: '2',
      proficiency: PROFICIENCY.EXPERIENCED,
      skills: [
        {
          id: '1',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Javascript',
          percent: 97,
        },
        {
          id: '2',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Typescript',
          percent: 90,
        },
        {
          id: '3',
          proficiency: PROFICIENCY.EXPERT,
          title: 'React-NativeJS',
          percent: 72,
        },
        {
          id: '4',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Xcode',
          percent: 68,
        },
        {
          id: '5',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Android Studio',
          percent: 62,
        },
        {
          id: '6',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Swift',
          percent: 67,
        },
        {
          id: '7',
          proficiency: PROFICIENCY.EXPERT,
          title: 'Kotlin',
          percent: 54,
        },
      ],
      summary:
        'Advanced level development skills with over 6+ years experience in development for mobile platforms using libraries like React Native and native development tools like Xcode and Android Studio',
      title: 'Mobile Development',
    },
    {
      id: '3',
      proficiency: PROFICIENCY.EXPERIENCED,
      skills: [
        {
          id: '1',
          proficiency: PROFICIENCY.EXPERIENCED,
          title: 'Python',
          percent: 67,
        },
        {
          id: '2',
          proficiency: PROFICIENCY.INTERMEDIATE,
          title: 'Flask',
          percent: 66,
        },
        {
          id: '3',
          proficiency: PROFICIENCY.INTERMEDIATE,
          title: 'Django',
          percent: 55,
        },
      ],
      summary:
        'In-depth knowledge and experience in the design and development embedded systems hardware and software',
      title: 'Embedded Systems Development',
    },
  ],
  skills: [
    {
      id: '1',
      proficiency: PROFICIENCY.INTERMEDIATE,
      title: 'Xcode',
      percent: 72,
    },
    {
      id: '2',
      proficiency: PROFICIENCY.INTERMEDIATE,
      title: 'Android Studio',
      percent: 73,
    },
    {
      id: '3',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'MongoDB',
      percent: 89,
    },
    {
      id: '4',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'MySQL',
      percent: 80,
    },
    {
      id: '5',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'Docker',
      percent: 81,
    },
    {
      id: '10',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'CI/CD',
      percent: 80,
    },
    {
      id: '6',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'ASP.NET-CORE',
      percent: 72,
    },
    {
      id: '7',
      proficiency: PROFICIENCY.EXPERT,
      title: 'NodeJS',
      percent: 91,
    },
    {
      id: '8',
      proficiency: PROFICIENCY.EXPERT,
      title: 'ReactJS',
      percent: 94,
    },
    {
      id: '9',
      proficiency: PROFICIENCY.EXPERT,
      title: 'React NativeJS',
      percent: 89,
    },
    {
      id: '11',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'Flask',
      percent: 52,
    },
    {
      id: '12',
      proficiency: PROFICIENCY.INTERMEDIATE,
      title: 'PCB Design & Fabrication',
      percent: 77,
    },
  ],
  languages: [
    {
      id: '1',
      proficiency: PROFICIENCY.EXPERT,
      title: 'English',
      percent: 90,
    },
    {
      id: '1',
      proficiency: PROFICIENCY.EXPERT,
      title: 'Yoruba',
      percent: 98,
    },
  ],
  links: [
    {
      id: '1',
      title: 'GitHub',
      url: 'https://github.com/DanielBello7',
    },
    {
      id: '2',
      title: 'X',
      url: 'https://x.com/i/flow/login?redirect_after_login=%2FOnlyBello_',
    },
    {
      id: '3',
      title: 'LinkedIn',
      url: 'https://www.linkedin.com/in/adegoke-bello-3397a3a6/',
    },
    {
      id: '4',
      title: 'Portfolio',
      url: 'https://danielbello.dev',
    },
  ],
  education: [
    {
      id: '1',
      country: 'Nigeria',
      start: '2014',
      end: '2019',
      school: 'Ekiti State University Ado Ekiti',
      certificate: 'B.Eng Computer Engineering',
      notes: ['Graduated with honors for best final project design'],
    },
  ],
  hobbies: [
    'Reading',
    'Research',
    'Coding',
    'Reading Manga',
    'Walking',
    'Listening to Music',
    'Gaming',
  ],
  other: {},
  socials: {
    github: 'https://github.com/DanielBello7',
    linkedin: 'https://www.linkedin.com/in/adegoke-bello-3397a3a6/',
    twitter:
      'https://x.com/i/flow/login?redirect_after_login=%2FOnlyBello_',
  },
  courses: [
    {
      id: '1',
      title:
        'Node.js & MongoDB: Developing Back-end Database Applications',
      organization: 'I.B.M',
      start: 'Jan 18, 2025',
      end: 'Jan 18, 2025',
      url: 'https://coursera.org/verify/LBYYFG7G4BES',
    },
    {
      id: '2',
      title: 'Introduction To Swift Programming',
      organization: 'University of Toronto',
      start: 'Feb 23, 2025',
      end: 'Feb 23, 2025',
      url: 'https://coursera.org/verify/I0MLUPLC64HA',
    },
    {
      id: '3',
      title: 'iOS App Development Basics',
      organization: 'University of Toronto',
      start: 'Apr 4, 2025',
      end: 'Apr 4, 2025',
      url: 'https://coursera.org/verify/5NF2NONVQCB2',
    },
    {
      id: '4',
      title: 'JavaScript Programming Essentials',
      organization: 'I.B.M',
      start: 'Apr 27, 2025',
      end: 'Apr 27, 2025',
      url: 'https://coursera.org/verify/JWDLD47E8TZY',
    },
  ],
  work_experience: [
    {
      id: '1',
      company_name: 'Freelance',
      country: 'Remote',
      end: 'Currently',
      start: 'Oct 2023',
      position_held: 'Full Stack Engineer',
      points: [
        'Built scalable web applications for clients across e-commerce, education, and logistics sectors using Next.js and Node.js.',
        'Integrated third-party APIs and developed custom REST/GraphQL endpoints for dynamic client needs.',
      ],
    },
    {
      id: '3',
      company_name: 'Gallery of Code',
      country: 'Nigeria',
      end: 'Feb 2024',
      start: 'Jun 2021',
      position_held: 'Full Stack Engineer',
      points: [
        'Introduced modular architecture for efficient code updates',
        'Engineered a custom caching solution, enhancing system efficiency by 25%.',
        'Contributed to team success in a collaborative environment',
      ],
    },
    {
      id: '2',
      company_name: 'Defence Space Administration',
      country: 'Nigeria',
      end: 'Oct 2023',
      start: 'Apr 2021',
      position_held: 'Software Engineer',
      points: [
        'Increased document security through local server setup',
        'Implemented end-to-end encryption system',
        'Engineered secure messaging platform for Defence Space Administration',
        'Pioneered a predictive maintenance tool for network servers.',
      ],
    },
    {
      id: '4',
      company_name: 'P.A.R.V.I',
      country: 'Nigeria',
      end: 'Feb 2022',
      start: 'Aug 2021',
      position_held: 'Product Engineer / System Architect',
      points: [
        'Pioneered a demo for a Learning Management System (LMS) product, securing 3+ investors',
        'Established operational structure and contributed to the hiring of 3 engineers',
        'Optimized applications frontend, reducing load time from 20s to 3s',
      ],
    },
  ],
  programming_languages: [
    {
      id: '1',
      proficiency: PROFICIENCY.EXPERT,
      title: 'Javascript',
      percent: 90,
    },
    {
      id: '2',
      proficiency: PROFICIENCY.EXPERT,
      title: 'Typescript',
      percent: 93,
    },
    {
      id: '3',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'Python',
      percent: 72,
    },
    {
      id: '4',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'C#',
      percent: 81,
    },
    {
      id: '5',
      proficiency: PROFICIENCY.EXPERIENCED,
      title: 'Swift',
      percent: 71,
    },
    {
      id: '6',
      proficiency: PROFICIENCY.INTERMEDIATE,
      title: 'Kotlin',
      percent: 64,
    },
  ],
  projects: [
    {
      id: '1',
      description:
        'A Simple and quick database to help development process and speed',
      github: 'https://github.com/DanielBello7/nosql-json-database',
      img: assets.nosql_json_database_1,
      previews: [assets.nosql_json_database_1],
      tags: ['Typescript', 'NodeJS', 'NPM', 'Database', 'Backend'],
      title: 'NoSQL Json Database',
      type: PROJECT_TYPE.BACKEND,
      url: 'https://www.npmjs.com/package/nosql-json-database',
      isCompleted: true,
      role: 'Backend',
    },
    {
      id: '2',
      description: 'A near perfect re-make for the figma store website.',
      github: 'https://github.com/DanielBello7/figma-website-clone',
      img: assets.figma_clone_1,
      previews: [assets.figma_clone_1],
      tags: ['Frontend', 'Typescript', 'ViteJS', 'ReactJS', 'NodeJS'],
      title: 'Figma Store Clone',
      type: PROJECT_TYPE.FRONTEND,
      url: 'https://figma.danielbello.dev',
      isCompleted: true,
      role: 'Frontend',
    },
    {
      id: '3',
      description:
        'A task manager to effortlessly manage tasks and get task metrics.',
      github: 'https://github.com/DanielBello7/time-tracker.git',
      img: assets.core_task_1,
      previews: [assets.core_task_1],
      tags: [
        'Full Stack',
        'NextJS',
        'Typescript',
        'Mongodb',
        'Backend',
        'Frontend',
      ],
      title: 'CoreTask Task Manager',
      type: PROJECT_TYPE.FULL_STACK,
      url: 'https://coretask.danielbello.dev',
      isCompleted: true,
      role: 'Full Stack',
    },
    {
      id: '4',
      description:
        'Portfolio Application showcasing resume and other projects',
      github: 'https://github.com/DanielBello7/portfolio.git',
      img: assets.portfolio_v1_1,
      previews: [assets.portfolio_v1_1],
      tags: ['Frontend', 'Vite', 'Javascript', 'Framer Motion'],
      title: 'Portfolio V1',
      type: PROJECT_TYPE.FRONTEND,
      url: 'https://portfolio-steel-seven-96.vercel.app/',
      isCompleted: true,
      role: 'Frontend',
    },
    {
      id: '5',
      description: 'API Backend for the bucket.space social media',
      github: 'https://github.com/DanielBello7/bucket-space-api.git',
      img: assets.bucket_1,
      previews: [assets.bucket_1],
      tags: [
        'Backend',
        'REST-API',
        'ExpressJS',
        'TypeORM',
        'SQL',
        'NodeJS',
        'Typescript',
      ],
      title: 'Bucket.Space API',
      type: PROJECT_TYPE.BACKEND,
      url: null,
      isCompleted: true,
      role: 'Backend',
    },
    {
      id: '6',
      description:
        'Backend API application for the HireUs staff management app',
      github: 'https://github.com/DanielBello7/hire-us-backend.git',
      img: assets.hireus_1,
      previews: [assets.hireus_1],
      tags: [
        'Backend',
        'NestJS',
        'API',
        'Docker',
        'Typescript',
        'SQL',
        'Prisma',
        'SQLite',
      ],
      title: 'HireUs API',
      type: PROJECT_TYPE.BACKEND,
      url: null,
      isCompleted: true,
      role: 'Backend',
    },
  ],
};
